import { readFileSync } from "node:fs";
import { join } from "node:path";
import { describe, expect, it } from "vitest";
import { schemaDoc, documentedColumns } from "./schema-doc";
import { ALLOWED_RELATIONS } from "./guard";

/**
 * The columns each `q_` view actually has, read out of the generated types.
 *
 * `@cigua/core/supabase/types` is generated by `supabase gen types` against the live
 * project, so it is the closest thing to the database this suite can reach
 * without a connection — and unlike a hand-written fixture it cannot be updated
 * to agree with a mistake.
 */
function generatedColumns(view: string): string[] {
  const types = readFileSync(join(import.meta.dirname, "../../../../../packages/core/src/supabase/types.ts"), "utf8");
  const section = new RegExp(`      ${view}: \\{\\n        Row: \\{([\\s\\S]*?)\\n        \\}`);
  const match = types.match(section);
  if (!match) throw new Error(`${view} is not in the generated types`);
  return [...match[1].matchAll(/^\s+(\w+):/gm)].map((m) => m[1]);
}

/**
 * Columns the document leaves out on purpose.
 *
 * `user_id` is the only one: every view carries it because the base tables do,
 * and the document's first instruction is that the model must never filter by it
 * or mention it — the views are already scoped by RLS. Documenting it would
 * invite exactly the query that instruction forbids.
 */
const DELIBERATELY_UNDOCUMENTED = new Set(["user_id"]);

describe("schemaDoc", () => {
  it("names every whitelisted view", () => {
    const doc = schemaDoc();
    for (const view of ALLOWED_RELATIONS) expect(doc).toContain(view);
  });

  it("documents every whitelisted view", () => {
    expect([...documentedColumns().keys()].sort()).toEqual([...ALLOWED_RELATIONS].sort());
  });

  it("tells the model which column answers a spending question", () => {
    expect(schemaDoc()).toMatch(/budget_spend[\s\S]{0,200}how much did I spend/i);
  });
});

/* The document is prose and the views are SQL, so nothing forces them to agree.
   Both directions of drift are silent and both read as the model being stupid:
   a column the document invented comes back as `column "x" does not exist` after
   the model confidently selected it, and a column the document forgot is one the
   model never uses — the feature quietly cannot answer a question it should.

   This is the test the spec promised and the plan shipped without. */
describe.each([...ALLOWED_RELATIONS])("%s stays in step with the database", (view) => {
  const documented = new Set(documentedColumns().get(view) ?? []);
  const generated = generatedColumns(view);

  it("documents nothing the view does not have", () => {
    expect([...documented].filter((c) => !generated.includes(c))).toEqual([]);
  });

  it("documents everything the view has", () => {
    const missing = generated.filter(
      (c) => !documented.has(c) && !DELIBERATELY_UNDOCUMENTED.has(c),
    );
    expect(missing).toEqual([]);
  });
});
